# Generated by Django 5.0.6 on 2024-07-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopaAmerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('sede', models.CharField(max_length=50)),
                ('campeon', models.CharField(max_length=50)),
                ('subcampeon', models.CharField(max_length=50)),
                ('goleador', models.CharField(max_length=50)),
                ('partidos_jugados', models.IntegerField()),
                ('goles_marcados', models.IntegerField()),
            ],
        ),
    ]
